name: Construir y Desplegar en GH-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Hola Mundo
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run multi-line scripts :B
        run: |
          echo Add other actions to build,
          
          echo " Print Node Version -------------------------------------"
          node -v
          
          echo " add hollo.md -------------------------------------"
          # touch hollo.md
          # git add hollo.md
          # git commit -m "add hollo"
          # git push master
          
          echo " LS -------------------------------------"
          ls -a
          
          echo " -------------------------------------"
          echo ver pwd:
          pwd
          
          
          echo " -------------------------------------"
          echo Creado y listado
          echo Print Git Version
          git --version
          echo "-------------------------------------"
          echo Print - http Curl
          echo "-------------------------------------"
          curl https://maker.ifttt.com/trigger/hookif/with/key/i2au2EIwBAZbkTwnyv4QEelN9Qn_SVjMlqcJ38gj2AD?value1=desdeGHd123
          echo Print GH verision
          gh --version
      
